# --- Main Colors ---
background            #1a1110
foreground            #f1dedc
cursor                #f1dedc
cursor_text_color     #1a1110

selection_background  #5d3f3b
selection_foreground  #ffdad5

url_color             #dfc38c

# --- ANSI Colors ---
color0                #1a1110
color1                #ffb4ab
color2                #dfc38c
color3                #e7bdb7
color4                #ffb4a9
color5                #dfc38c
color6                #e7bdb7
color7                #f1dedc

color8                #534341
color9                #93000a
color10               #574419
color11               #5d3f3b
color12               #73342c
color13               #5d3f3b
color14               #574419
color15               #d8c2be

# --- Starship Prompt Bubbles ---
color255              #73342c
color254              #ffb4a9
color253              #5d3f3b
color252              #e7bdb7
color251              #574419
color250              #dfc38c
color249              #93000a
color248              #ffb4ab

color232              #ffdad5
color233              #561e18
color234              #ffdad5
color235              #442926
color236              #fcdfa6
color237              #3e2e04
color238              #ffdad6
color239              #690005
color240              #ffdad5

# Matched with unthemed light/dark
color243              #ffb4a9
color244              #ffb4ab
color245              #534341

# --- UI Elements ---
active_tab_foreground   #561e18
active_tab_background   #ffb4a9
inactive_tab_foreground #ffdad5
inactive_tab_background #73342c

active_border_color     #ffb4a9
inactive_border_color   #a08c89

# --- Marks ---
mark1_foreground        #3b0906
mark1_background        #ffdad5
mark2_foreground        #2c1512
mark2_background        #ffdad5
mark3_foreground        #261a00
mark3_background        #fcdfa6

