# --- Main Colors ---
background            #1a1110
foreground            #f1dedc
cursor                #f1dedc
cursor_text_color     #1a1110

selection_background  #5d3f3c
selection_foreground  #ffdad6

url_color             #e1c38c

# --- ANSI Colors ---
color0                #1a1110
color1                #ffb4ab
color2                #e1c38c
color3                #e7bdb8
color4                #ffb3ac
color5                #e1c38c
color6                #e7bdb8
color7                #f1dedc

color8                #534342
color9                #93000a
color10               #584419
color11               #5d3f3c
color12               #73332f
color13               #5d3f3c
color14               #584419
color15               #d8c2bf

# --- Starship Prompt Bubbles ---
color255              #73332f
color254              #ffb3ac
color253              #5d3f3c
color252              #e7bdb8
color251              #584419
color250              #e1c38c
color249              #93000a
color248              #ffb4ab

color232              #ffdad6
color233              #571e1a
color234              #ffdad6
color235              #442927
color236              #fedea6
color237              #402d04
color238              #ffdad6
color239              #690005
color240              #ffdad6

# Matched with unthemed light/dark
color243              #ffb3ac
color244              #ffb4ab
color245              #534342

# --- UI Elements ---
active_tab_foreground   #571e1a
active_tab_background   #ffb3ac
inactive_tab_foreground #ffdad6
inactive_tab_background #73332f

active_border_color     #ffb3ac
inactive_border_color   #a08c8a

# --- Marks ---
mark1_foreground        #3b0908
mark1_background        #ffdad6
mark2_foreground        #2c1513
mark2_background        #ffdad6
mark3_foreground        #261900
mark3_background        #fedea6

