# --- Main Colors ---
background            #121318
foreground            #e3e1e9
cursor                #e3e1e9
cursor_text_color     #121318

selection_background  #424659
selection_foreground  #dee1f9

url_color             #e3bada

# --- ANSI Colors ---
color0                #121318
color1                #ffb4ab
color2                #e3bada
color3                #c2c5dd
color4                #b6c4ff
color5                #e3bada
color6                #c2c5dd
color7                #e3e1e9

color8                #45464f
color9                #93000a
color10               #5b3d57
color11               #424659
color12               #354479
color13               #424659
color14               #5b3d57
color15               #c6c6d0

# --- Starship Prompt Bubbles ---
color255              #354479
color254              #b6c4ff
color253              #424659
color252              #c2c5dd
color251              #5b3d57
color250              #e3bada
color249              #93000a
color248              #ffb4ab

color232              #dce1ff
color233              #1d2d61
color234              #dee1f9
color235              #2b3042
color236              #ffd7f6
color237              #432740
color238              #ffdad6
color239              #690005
color240              #dce1ff

# Matched with unthemed light/dark
color243              #b6c4ff
color244              #ffb4ab
color245              #45464f

# --- UI Elements ---
active_tab_foreground   #1d2d61
active_tab_background   #b6c4ff
inactive_tab_foreground #dce1ff
inactive_tab_background #354479

active_border_color     #b6c4ff
inactive_border_color   #90909a

# --- Marks ---
mark1_foreground        #03174b
mark1_background        #dce1ff
mark2_foreground        #161b2c
mark2_background        #dee1f9
mark3_foreground        #2c122a
mark3_background        #ffd7f6

