################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor = DP-4, 3840x2160, 0x0, 1.25
monitor = HDMI-A-2, 1920x1080, 3072x0, 1

# Workspaces 1-5 on main monitor
workspace = 1, monitor:DP-4
workspace = 2, monitor:DP-4
workspace = 3, monitor:DP-4
workspace = 4, monitor:DP-4
workspace = 5, monitor:DP-4

# Workspaces 6-10 on seconary monitor
workspace = 6, monitor:HDMI-A-2
workspace = 7, monitor:HDMI-A-2
workspace = 8, monitor:HDMI-A-2
workspace = 9, monitor:HDMI-A-2
workspace = 10, monitor:HDMI-A-2





















